
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Fundgrid.Data
{

using System;
    using System.Collections.Generic;
    
public partial class grid_item
{

    public int id { get; set; }

    public Nullable<int> number { get; set; }

    public string owner { get; set; }

    public Nullable<decimal> amount { get; set; }

    public Nullable<int> grid_id { get; set; }



    public virtual grid grid { get; set; }

}

}
