//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundgrid.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.grids = new HashSet<grid>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] image { get; set; }
        public string owner_id { get; set; }
    
        public virtual ICollection<grid> grids { get; set; }
    }
}
